name: Generate Json

on:
  schedule:
    - cron: '30 */3 * * *'
  workflow_dispatch:
  repository_dispatch:
    branches:
      - main
    types: [new-release]

jobs:
  generate:
    name: Generate Repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: 'pypy3.10'

      - name: Run Python Script
        run: |
          python publish.py

      - name: Commit Files
        continue-on-error: true
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -A
          git commit -m "Regenerate Repo" --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
      
      - name: Push Changes
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: main